# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.9.0'
git_version = '971632833036c576cf95499291f689f8bb3519e1'
