# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.8.0'
git_version = 'db9a0e8b604026eda3975375f2261c4d49009eea'
